version: '3.8'

services:
    tournydev:
      container_name: tournydev
      # depends_on:
      #   - gopherdb
      build:
        context: ../
        dockerfile: docker/Dockerfile
      image: tournydev
      volumes:
      - ../:/app
      - /app/node_modules/
      - /app/.next/
      restart: always
      ports:
        - 3001:3000
        - 9229:9229
      # networks:
      #   - gophernetwork